//! Quai Terminal engine: identity, networks, state and wallet services shared by the CLI and TUI.

pub mod alerts;
pub mod amount;
pub mod anchor;
pub mod appdb;
pub mod capabilities;
mod chain;
pub mod chainstats;
pub mod chat;
pub mod cockpit;
mod commitments;
pub mod config;
pub mod contracts;
pub mod curve;
pub mod data;
pub mod diag;
pub mod error;
pub mod execution;
pub mod explorer;
pub mod extras;
pub mod flows;
pub mod gauge;
pub mod hartii;
pub mod hartii_tx;
pub mod http;
pub mod identity;
pub mod ipfs;
pub mod journal;
pub mod launches;
pub mod liquidity;
pub mod market;
pub mod markets;
pub mod media;
pub mod media_helper;
pub mod messages;
pub mod messaging;
pub mod multicall;
pub mod network;
pub mod nft_uri;
pub mod ops;
pub mod orders;
pub mod paths;
pub mod plans;
pub mod pnl;
pub mod portfolio;
pub mod qi_exit;
pub mod qi_market;
pub mod recipient;
mod recovery;
pub mod registry;
pub mod routes;
pub mod ser;
pub mod session;
#[cfg(test)]
mod testutil;
pub mod spendable;
pub mod split_routes;
pub mod subgraph;
pub mod swap;
pub mod track;
pub mod tx;
pub mod zone;

pub use error::{CoreError, Result};
pub use quai_sdk as sdk;
